### ISSUE TITLE
`mode-watcher` not working for a fresh project

### ISSUE THREAD

**Issue by shyakadavis** [huntabyte/mode-watcher#12]
Hi, @huntabyte 

Thanks for this. Been finding some hacks occasionally to make this work.

That said, the package is not working for me.

Context:

I just created a new repo, following the `shadcn-svelte` docs, and then proceeded to add `mode-watcher`.

I don't know why, but the package is not working for me. I tried to see if it's an issue with my browser, and tried others, but all failed.

- I tried these browsers: `Firefox (both standard & for devs) | Safari | Arc | Chrome`, but nothing.

- I also noticed, that when toggling the theme, system-wise, (I'm on Mac), the class name is not toggled and stays as to how it was you first hit the url. 

I don't know if you require any more context, but if any, please let know.

**Comment by ollema** [comment]
can you share a reproduction? installing `mode-watcher`, adding the `<ModeWatcher>` component and calling for example `setMode` or `toggleMode` works for me

**Comment by ollema** [comment]
> I also noticed, that when toggling the theme, system-wise, (I'm on Mac), the class name is not toggled and stays as to how it was you first hit the url.

aha, just saw this. listening for live changes in the system-wise theme is not supported by `mode-watcher` out of the box right now. if you toggle the system-wise theme, you should be able to see the theme change if you perform a hard refresh of the site.

I can try to add this functionality today

**Comment by shyakadavis** [comment]
Hey, @ollema 

Thanks for the reply.

So, here's my `app.postcss`:

```css
/* Supports weights 100-900 */
@import '@fontsource-variable/inter';

@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
	:root {
		--background: 0 0% 100%;
		--foreground: 240 10% 3.9%;

		--muted: 240 4.8% 95.9%;
		--muted-foreground: 240 3.8% 46.1%;

		--popover: 0 0% 100%;
		--popover-foreground: 240 10% 3.9%;

		--card: 0 0% 100%;
		--card-foreground: 240 10% 3.9%;

		--border: 240 5.9% 90%;
		--input: 240 5.9% 90%;

		--primary: 240 5.9% 10%;
		--primary-foreground: 0 0% 98%;

		--secondary: 240 4.8% 95.9%;
		--secondary-foreground: 240 5.9% 10%;

		--accent: 240 4.8% 95.9%;
		--accent-foreground: 240 5.9% 10%;

		--destructive: 0 84.2% 60.2%;
		--destructive-foreground: 0 0% 98%;

		--ring: 240 10% 3.9%;

		--radius: 0.5rem;
	}

	.dark {
		--background: 240 10% 3.9%;
		--foreground: 0 0% 98%;

		--muted: 240 3.7% 15.9%;
		--muted-foreground: 240 5% 64.9%;

		--popover: 240 10% 3.9%;
		--popover-foreground: 0 0% 98%;

		--card: 240 10% 3.9%;
		--card-foreground: 0 0% 98%;

		--border: 240 3.7% 15.9%;
		--input: 240 3.7% 15.9%;

		--primary: 0 0% 98%;
		--primary-foreground: 240 5.9% 10%;

		--secondary: 240 3.7% 15.9%;
		--secondary-foreground: 0 0% 98%;

		--accent: 240 3.7% 15.9%;
		--accent-foreground: 0 0% 98%;

		--destructive: 0 62.8% 30.6%;
		--destructive-foreground: 0 0% 98%;

		--ring: 240 4.9% 83.9%;
	}
}

@layer base {
	* {
		@apply border-border relative;
	}

	html,
	body {
		@apply h-full;
	}

	body {
		@apply bg-background text-foreground antialiased font-sans;
		font-feature-settings:
			'rlig' 1,
			'calt' 1;
	}
}
```

I expected the `dark` css variabled to replace the default ones when the system changes to dark.

This is not what happens. The default css vars still remain. I literally just created 2 new projects using `shadcn-svelte` to test this, but they all behave like this. It's very strange to be honest. 😅 

> @shyakadavis could you try and clarify exactly what is not working? is it only the automatic changing whenever the system theme changes or is nothing working at all (even on hard refresh or when changing the mode with setMode or toggleMode or resetMode

- So, automatic changing does not work, and hard refresh doesn't work either.
- What works, is manually toggling the theme, and in the `html` doc, the `dark` class gets toggled. But the issue is, the css variables aren't swapped. I have no idea why.

Does this make sense, or should share the repo? Also, if you would be so kind, could you share the repo where it works forr you. Perhaps I messed up somewhere or we have different config files. I want to compare.

Thank you.
